### ISSUE TITLE
go get github.com/RTradeLtd/Temporal taking extraordinarily long time

### ISSUE THREAD

**Issue by evscott** [RTradeLtd/Temporal#217]
As per the README's build instructions, I'm attempt to run 'go get github.com/RTradeLtd/Temporal' and the process seems to never end. From what I've gathered online, this seems to be an issue inherent to go when it's acting on large projects. Is there a current estimate as to how long this process _should_ take though?

**Comment by evscott** [comment]
After about 15 minutes this message is displayed:

> package github.com/RTradeLtd/Temporal: no Go files in /Users/eliotscott/go/src/github.com/RTradeLtd/Temporal

I've ran this process twice on my machine that's running osx10.14 Mojav with go version go1.10.2 darwin/amd64.

**Comment by postables** [comment]
At the moment I don't think there's anyway around this at the moment, and unfortunately isn't likely to change anytime soon :disappointed: 

I will update the README indicating that this should be expected. Thanks for bringing this up!
