### ISSUE TITLE
Allow User Or Email Sign In

### ISSUE THREAD

**Issue by postables** [RTradeLtd/Temporal#334]
# Assignee: [@arku](https://github.com/arku)

**Why are you submitting this feature request**
Sign-in can only be done via username 

**Describe the solution you'd like**
Allow specifying the username or email as a sign in method to be combined with password

**Comment by arku** [comment]
@postables I would like to take a stab at this issue.

**Comment by postables** [comment]
Sound's good I'll assign it to you, thanks :muscle:
