### ISSUE TITLE
Enable Email SignIn's From Database

### ISSUE THREAD

**Issue by postables** [RTradeLtd/Temporal#349]
With [#334](https://github.com/RTradeLtd/Temporal/issues/334) being completed, we are now ready to enable email-sign ins.

This will require updating dependency of `RTradeLtd/database` to `v2.4.0`

**Comment by arku** [comment]
@postables  I am on it.

**Comment by postables** [comment]
Closed by https://github.com/RTradeLtd/Temporal/pull/352
