### ISSUE TITLE
POST login query using native javascript browser fetch or xhr are rejected with CORS not same origin policy

### ISSUE THREAD

**Issue by chisNaN** [RTradeLtd/Temporal#364]
**Describe the bug**

POST login query using native javascript browser fetch or xhr are rejected with CORS not same origin policy.
So temporal cloud servers (on this part of this API) are restricted to the SAME ORIGIN policy.

(I "presume" this is a bug because otherwise i dont see why the documentation would give a sample of code suggesting the possibility of doing such action)

**To Reproduce**

1) Take the "official" code from the documentation api available here
https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/account.html#post-login
2) Insert valid credentials in the sample code (tested before with a classic login on the platform)
3) Execute the code in a javascript browser environment AND from a domain that is not temporal.cloud or any other subdomains of temporal.cloud

**Expected behavior**
As the API documentation display a solution with a native XHR 100% browser javascript,
the average front end web developer (like me) expect or make the assumption that this endpoint api will be accessible from any domain
and so will return the information about the session and token

**Screenshots**

**Additional context**

I can do nevertheless a simple XHR or fetch NATIVE BROWSER (e.g opening my browser console from within your domain) only from within the TLD temporal.cloud or any other subdomains authorized
otherwise the query will be rejected

I dont know if i am alone experiencing this issue
but my unique solution for now is to send my post login request (which will come obviously from another domain than temporal.cloud) thru a serverless proxy serversided script service like aws lambda or webtask.io

**Comment by postables** [comment]
Thanks for the detailed bug report, will be looking into this today :ok_hand:

**Comment by xiegeo** [comment]
@chisNaN I am unable to reproduce. Can you show me your request and response headers and reproducer? You can send it to my email at `georgex@rtradetechnologies.com` or post it here with your account credentials removed.

**Comment by chisNaN** [comment]
Thanks for your reactivity.
Right now it is working and i have no more cors rejection on this part of this api
(i presume there was something "temporally" wrong in the server like cache etc during an update or something like this)
Nevertheless after thinking about the possibility to fetch post login in js browser there are little chances the developer would apply that scenario because its credentials would be clearly visible
(Unless for an application to be used personally from home or kinda intranet)
Thanks again

**Comment by postables** [comment]
Credentials are never visible. A JWT authentication header is used, and headers are encrypted as part of the authentication process.
