### ISSUE TITLE
Review Documentation And Add Setup Procedures

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/Temporal#389]
Thanks to @NukeManDan  for pointing out that the docs need some TLC.

 Stuff I need to do:

* Update the docker-compose installation procedure
* Include a "getting started" for how to manually download and setup
* Include a "getting started" for how to download the releases and setup
* Link to the Temporal documentation "production setup" 
* Add check for Golang version
* not sure if I'm missing anything???

**Comment by NukeManDan** [comment]
I will use this issue to track my progress on installing bugs with you :grin:

**Comment by NukeManDan** [comment]
following along here: https://rtradetechnologies.atlassian.net/wiki/spaces/TEM/pages/55083603/Installing+Temporal+In+Production

* README needs to reflect this or direct to it/another walkthrough to get started.

**Comment by NukeManDan** [comment]
- add this to makefile : https://github.com/RTradeLtd/Temporal/blob/master/.travis.yml#L17-L18
- need `make` to run correctly with no further (or at least non-documented) config on a fresh install :wink:

**Comment by NukeManDan** [comment]
- you'll need go 1.12+ , so need check and indication in the docs of this

**Comment by NukeManDan** [comment]
- need to run temporal -config /path/to/file.json init but keep this file SECERET (or delete after use?)
  - temporal -config /tmp/config.json init
- alternatively set the environment variable CONFIG_DAG to your config file location

put the above into make file routine?

**Comment by NukeManDan** [comment]
- make file should include `make install` that moves into `bin` and sets `PATH`

**Comment by bonedaddy** [comment]
>     * add this to makefile : https://github.com/RTradeLtd/Temporal/blob/master/.travis.yml#L17-L18

done

>     * need `make` to run correctly with no further (or at least non-documented) config on a fresh install wink

`make install`  now takes care of this. We run `make` to perform some general health-checks of the codebase.

>     * you'll need go 1.12+ , so need check and indication in the docs of this in main repo and [testenv readme](https://github.com/RTradeLtd/testenv)

An install from source script has been created that performs these checks

>     * need to run temporal -config /path/to/file.json init but keep this file SECERET (or delete after use?)
>       
>       * temporal -config /tmp/config.json init
> 
>     * alternatively set the environment variable CONFIG_DAG to your config file location
> 
> 
> put the above into make file routine?

`make install` now takes care of this

>     * make file should include `make install` that moves into `bin` and sets `PATH`

done
