### ISSUE TITLE
Return hash when adding duplicate file

### ISSUE THREAD

**Issue by DallasC** [RTradeLtd/Temporal#420]
**Why are you submitting this feature request**
When adding a file with the api that is already uploaded to your account you currently get the following response 
``` JSON
{ 
    "code":400,
    "response":"it seems like you have uploaded content matching this hash already. To save your credits, no charge was placed and the call was gracefully aborted. Please contact support@rtradetechnologies.com if you believe this is an issue"
}
```

**Describe the solution you'd like**
It would be nice if in addition to the above message that the hash would also be provided and a 200 code would be returned. 

Something like
``` JSON
    "code": 200,
    "response": "<HASH VALUE>"
    "notice": "it seems like you have uploaded content matching this hash already. To save your credits, no charge was placed and the call was gracefully aborted. Please contact support@rtradetechnologies.com if you believe this is an issue"
```
This would be useful so that api clients can still return the response like making a successful upload instead of having to error out.

**Comment by u5surf** [comment]
@DallasC @bonedaddy 
I added the file hash value in `response` message. but I don’t have any knowhow that is to be tested whether response including a hash or not. Can you tell me the how to implement an end to end test with api server?

**Comment by xiegeo** [comment]
@u5surf 
A few issues in your change:
- Change `http.StatusBadReques` to `http.StatusOK`
- Use [Respond](https://godoc.org/github.com/RTradeLtd/Temporal/api/v2#Respond) to send json instead of formated string.

Feel free to create a pull request.

As for testing, docker is the easiest to set up. You can check out [.travis.yml](https://github.com/RTradeLtd/Temporal/blob/master/.travis.yml) for how it's done.

**Comment by Clay-Ferguson** [comment]
FYI, I also needed this feature. Any idea when this will be live on temporal.cloud ?

**Comment by bonedaddy** [comment]
The IPFS HTTP API already has it, i can open up a PR to implement the functionality into temporal's api tonight

**Comment by Clay-Ferguson** [comment]
That's awesome! I'll also implement it right away into quantizr.com once ready.

**Comment by bonedaddy** [comment]
@Clay-Ferguson @DallasC so I'm only changing things for file uploads right now. I'm unsure about making the change to the pin requests, but I'm open to suggestions.

**Comment by bonedaddy** [comment]
@Clay-Ferguson this update is now in our development environment so if you're using that now would be a good time to test, reminder though the IPFS HTTP API already has this, and this latest fix is **just** for accessing "Temporal's API" (the api you access via https://api.temporal.cloud)

**Comment by Clay-Ferguson** [comment]
That's great! I'll try it out tonight or tomorrow, and let you know how it goes.

**Comment by Clay-Ferguson** [comment]
So are you saying it is, or is *not* fixed at this address?

https://api.temporal.cloud/v2/ipfs/public/file/add

**Comment by bonedaddy** [comment]
Until its in production no. I guess what I said was a bit confusing. I meant that the fix only applies to Temporal's API, as the IPFS HTTP API already has this functionality. At the moment the fix is only rolled out to dev (https://dev.api.temporal.cloud) but will be available in prod sometime within the next 1 -> 2 weeks depending on if people report any breaks with dev.

**Comment by Clay-Ferguson** [comment]
My prod credentials don't seem to work for authenticating on dev, so let me know if I need to get dev credentials somehow, or just wait until you put it in prod. Thanks. Sorry for the hassle.

**Comment by DallasC** [comment]
The dev environment uses a different account so you're probably going to have to register a new dev account. You can use the same creditials or different ones, the two systems are different and use different databases. 

To register you can do it online at [dev.temporal.cloud](https://dev.temporal.cloud) or by using the [accounts api](https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/account.html#account-api). When using the API to register or test request make sure you are sending the requests to `dev.api.temporal.cloud` and not the normal API endpoint.

**Comment by Clay-Ferguson** [comment]
Thanks @DallasC, I created a dev account and tested, and I see it working perfectly now.

**Comment by bonedaddy** [comment]
Going to give this another 3-4 days of testing and roll it out

**Comment by bonedaddy** [comment]
The update should be live in production now, did some testing and everything was looking good, including our new playground correctly handling this case.

If this issue happens again please open a new issue. Thanks for your patience everyone :pray:
