### ISSUE TITLE
CORS on Chrome 

### ISSUE THREAD

**Issue by DallasC** [RTradeLtd/Temporal#424]
**Describe the bug**
When sending a request to the ipfs http api from a chrome browser you get the following CORS error:
```
Access to fetch at 'https://dev.api.ipfs.temporal.cloud/api/v0/add?stream-channels=true' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:3000, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
It appears that the header is being assigned twice and should just be assigned `*`.

**To Reproduce**
1. send a request from a chrome browser to `/api/v0/add` endpoint
2. In the Developer Tools Console in the browser

**Screen Shots**
Response headers
![Screen Shot 2019-12-23 at 3 25 30 PM](https://user-images.githubusercontent.com/2628528/71342844-ebd3bb80-2598-11ea-87da-6a1c3fa2f1a1.png)

Console Warning
![Screen Shot 2019-12-23 at 3 30 35 PM](https://user-images.githubusercontent.com/2628528/71342963-410fcd00-2599-11ea-90f8-8c88cd2ea039.png)

**Additional context**
This does not appear to be an issue with Firefox which I can still get a `200 Ok` response code. I have not tested on other browsers yet.

**Comment by bonedaddy** [comment]
solved with latest release of warp
