### ISSUE TITLE
GET[https://api.ipfs.temporal.cloud/api/v0/dns/ipfs.io] fails with http code 403 (forbidden)

### ISSUE THREAD

**Issue by chaingrok** [RTradeLtd/Temporal#441]
**Describe the bug**

The [Temporal gist](https://gist.github.com/bonedaddy/55be1cf00e8ffafff6e663c198bf6482) announces api/v0/dns as supported. It seems to be blocked by some missing authorization as we get FORBIDDEN (403)

**To Reproduce**

GET[https://api.ipfs.temporal.cloud/api/v0/dns/ipfs.io] with proper JWT

**Expected behavior**
Obtain same response that is obtained on our local IPFS server:

{
  "Path": "/ipfs/bafybeie5rfdrwsbg5iwrsmilgu4xvmkwnpvk7caih2vbupobjfajf5ketq"
}

**Comment by bonedaddy** [comment]
Strange this call should be allowed. I will debug this

**Comment by bonedaddy** [comment]
Looks like you sent the call incorrectly. Here's the log with sensitive information removed

```
{"level":"error","ts":1580674679.198572,"logger":"server","caller":"server/server.go:249","msg":"failed to get user from jwt","error":"no authentication provided","stacktrace":"github.com/RTradeLtd/warp/server.(*Server).handleProxyCall\n\t/BUILD/server/server.go:249\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/go-chi/chi.(*Mux).routeHTTP\n\t/BUILD/vendor/github.com/go-chi/chi/mux.go:425\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/go-chi/chi/middleware.Recoverer.func1\n\t/BUILD/vendor/github.com/go-chi/chi/middleware/recoverer.go:35\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/RTradeLtd/warp/log.loggerMiddleware.Handler.func1\n\t/BUILD/log/middleware.go:26\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/go-chi/chi/middleware.RealIP.func1\n\t/BUILD/vendor/github.com/go-chi/chi/middleware/realip.go:34\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/go-chi/chi/middleware.RequestID.func1\n\t/BUILD/vendor/github.com/go-chi/chi/middleware/request_id.go:72\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/go-chi/cors.(*Cors).Handler.func1\n\t/BUILD/vendor/github.com/go-chi/cors/cors.go:199\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/go-chi/chi.(*Mux).ServeHTTP\n\t/BUILD/vendor/github.com/go-chi/chi/mux.go:82\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}
{"level":"info","ts":1580674679.198821,"logger":"server.request.middleware","caller":"log/middleware.go:33","msg":"request completed","path":"/api/v0/dns/ipfs.io","query":"","method":"HEAD","took":0.00029734,"real-ip":"","request-id":"delta-node-2/Su82LGfqFg-001665"}
```

For whatever reason when you sent the request you didnt include the JWT in your authorizatino headers. One thing to keep in mind, in the past i've used clients like `js-ipfs-http-client` and `go-ipfs-api` and one certain calls they wouldn't inject the header information.

**Comment by bonedaddy** [comment]
Based on my findings in the previous comment, there is no clear indication that this problem is on our end, and is most likely one of the following:

* API request didnt include the authentication header
* IPFS HTTP API library being used has a reoccurence of previous bugs I've experienced.

I'm going to close this issue as such, however if you continue to experience this issue please re-open and provide sample code that shows how you are constructing the client, and making the call.
