### ISSUE TITLE
Data usage being double counted when uploading the same file

### ISSUE THREAD

**Issue by DallasC** [RTradeLtd/Temporal#455]
**Describe the bug**
Data usage is counted when uploading a file that has already been uploaded before even though the same hash is being returned.

**To Reproduce**
1. Upload a directory to temporal using the ipfs-http-client > get hash returned
2. Upload the same directory again > same hash is returned
3. Data Usage rate has been counted for each upload

**Expected behavior**
Since the same hash is being used the data usage should remain the same

**Comment by bonedaddy** [comment]
This should be an easy fix in warp I think. Not sure why the bug is happening but I'll do a fix today
