### ISSUE TITLE
GET Uploads response not correctly labeling directories

### ISSUE THREAD

**Issue by Vikkkkk** [RTradeLtd/Temporal#457]
**Describe the bug**
GET Uploads call returns `Directory:false` for a directory

**To Reproduce**
1. make the GET Uploads Api call
2. View the response for a directory uploaded or upload a new directory

**Expected behavior**
 Should be Directory:True

**Comment by bonedaddy** [comment]
Thanks, working on this now. Looks like the way directory uploads are done via the web browser is different than the cli, so my current method of detection is working with cli, but not uploads through the new playground.

**Comment by bonedaddy** [comment]
Alright I talked with @DallasC and we're going to work around this by doing header detection for browser based directory upload.

**Comment by bonedaddy** [comment]
This should be fixed now. Reopen if it happens again
