### ISSUE TITLE
Please unlock MetaMask

### ISSUE THREAD

**Issue by sixcorners** [RTradeLtd/Temporal#460]
**Describe the bug**
I can't get past the "Please unlock MetaMask." message on the RTC dashboard.

**To Reproduce**
1. Have metamask ready to go
2. Go to https://play.temporal.cloud/rtc

**Additional context**
I don't know that much about RTC. I'm pretty sure my metamask is unlocked.

**Comment by bonedaddy** [comment]
Metamask on that website is no longer functional. In order to pay for credits with metamask you'll need to use the new experimental playground

https://play2.temporal.cloud which will be replacing the playground

**Comment by bonedaddy** [comment]
Also technically you can use metamask on the current playground but it doesn't respect metamask privacy settings.

The solution to this is to alter the metamask privacy setting that makes it so websites are required to prompt you to unlock your account.

The downside to this is that if you don't disable this afterwards metamask will be injecting itself everywhere.

The solution to this is to use play2 until that supersedes play.temporal.cloud later this month or early next.

**Comment by sixcorners** [comment]
Seems that running `ethereum.enable()` in the dev console gets it running. Also the new website looks good.

**Comment by bonedaddy** [comment]
Interesting never knew that was possible. I'm going to close this now, if you run into any issues create a new issue referencing this one.

Thanks! Feel free to give your feedback in our telegram, negative feedback is ok as long as it's constrictive.
