### ISSUE TITLE
play.temporal.cloud not updating

### ISSUE THREAD

**Issue by Clay-Ferguson** [RTradeLtd/Temporal#461]
I uploaded an image (QmX74CAk2V3qxMRTwgCoboH732CRoFGkXZWALV9vKKA1BE) using the javascript HTTP Api, and it successfully got uploaded, and is accessible via IPFS, however the website for my account is not showing that file at all, here https://play.temporal.cloud/uploads.

Is this normal? Shouldn't the website console show all my files regardless of which method I used to upload?

**Comment by bonedaddy** [comment]
This is intended, the view there is generated from uploads done through that website (https://play.temporal.cloud). That website is being deprecated in favour of https://play2.temporal.cloud, if you go to the new website or use the uploads api calls (https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/database.html#uploads) you'll see the upload.

**Comment by Clay-Ferguson** [comment]
Thanks! I missed the "Detailed Information" section or I'd have seen it. My apologies. 

It's great to also know about the new interface and the API call also. Appreciate you mentioning that.

**Comment by bonedaddy** [comment]
> Thanks! I missed the "Detailed Information" section or I'd have seen it. My apologies.
> 
> It's great to also know about the new interface and the API call also. Appreciate you mentioning that.

Eh no apologies needed the old website was a bit confusing in layout. 

> It's great to also know about the new interface and the API call also. Appreciate you mentioning that.

No problem, we'll be making a formal announcement about the new website when it's done which shouldn't be longer than a month or so.

Going to close this issue, but feel free to  open another one if something pops up. We've also got a [telegram chat](https://t.me/RTradeTEMPORAL) too for "live support"
