### ISSUE TITLE
---> Our IP Addresses Have Changed! <---

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/Temporal#481]
Our glorious ISP wanted to do some migrations and change our static ip addresses. As such all IP addresses at our datacenter have now been switched over to the new addresses assigned to us by our ISP. 

If you're hitting any of our services via IP addresses directly, it's highly recommended that you switch to using our DNS names as they're setup for HA in the event of a failure, but if you want to continue using IP Addresses simple change `172.218.49.115` to `207.6.222.55` and you'll be good to go. The exception to this is connecting to our IPFS nodes for which using IP addresses are recommended over DNS names

[We've also updated our bootstrap helper package to include our new ip addresses](https://github.com/RTradeLtd/bootstrap/blob/master/bootstrap.go#L20)

**Comment by pedrovagner** [comment]
@bonedaddy why I can't create an account via web interface? Is this service available?

**Comment by bonedaddy** [comment]
@pedrovagner unfortunately the project is shutting down [see this tweet](https://twitter.com/Temporalcloud/status/1347452505341317120) for more information.
