### ISSUE TITLE
Should update IPFS documentation about POST https dL endpoint port 6767 returning SSL CERT error

### ISSUE THREAD

**Issue by chisNaN** [RTradeLtd/Temporal#488]
**Describe the bug**
POST IPFS download HTTPS endpoint port 6767 returning SSL CERT error
https://api.temporal.cloud:6767/v2/ipfs/utils/download/
ACTUALLY a workaround is to SKIP the port right now
**To Reproduce**
1. Go to the official doc https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/ipfs.html#post-download-file
2. Try the sample javascript
3. See error

**Expected behavior**
No ssl cert error

**Additional context**
it used to work on port 6767 as described on the doc here
https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/ipfs.html#post-download-file
ACTUALLY a workaround is to SKIP the port right now

**Comment by xiegeo** [comment]
@bonedaddy it looks like the server is not loading the updated certificate. Maybe a restart?

**Comment by xiegeo** [comment]
@chisNaN I think you are right, please don't use that port anymore. I'll update the documentation after confirmation form @bonedaddy

**Comment by chisNaN** [comment]
thanks @xiegeo for your reactivity
